package stamina
package testkit

import org.scalatest._

class ScalatestTestGenerationSpec extends StaminaTestKitSpec {

  "A spec generated by StaminaTestKit" should {
    val spec = new StaminaTestKit with WordSpecLike {

      "fo" should {

        "bar" in {
        }
      }
    }

    "generate tests for serialization roundtrips" in {
      println(spec.testNames)
    }
  }

}
